package mod.leronus.mores.item;

import mod.leronus.mores.Mores;
import mod.leronus.mores.block.ModBlocks;
import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;

public class ModItemGroups {
    public static final ItemGroup MATERIAL_GROUP = Registry.register(Registries.ITEM_GROUP,
            Identifier.of(Mores.MOD_ID, "materials"),
            FabricItemGroup.builder().displayName(Text.translatable("creativemodetab.mores_materials"))
                    .icon(() -> new ItemStack(ModItems.RUBY_GEM)).entries((displayContext, entries) -> {
                       entries.add(ModItems.ANTHRACITE);
                       entries.add(ModItems.TURQUOISE);
                       entries.add(ModItems.CITRINE);
                       entries.add(ModItems.ONYX);

                       entries.add(ModItems.OBSIDIAN_UPGRADE_SMITHING_TEMPLATE);
                       entries.add(ModItems.HARDENED_STEEL_UPGRADE_SMITHING_TEMPLATE);
                       entries.add(ModItems.ADAMANTIUM_UPGRADE_SMITHING_TEMPLATE);
                       entries.add(ModItems.ENDERITE_UPGRADE_SMITHING_TEMPLATE);

                       entries.add(ModItems.RAW_TIN);
                       entries.add(ModItems.RAW_SILVER);
                       entries.add(ModItems.RAW_COBALT);

                       entries.add(ModItems.HOT_CARBON_STEEL_SCRAP);
                       entries.add(ModItems.CARBON_STEEL_SCRAP);
                       entries.add(ModItems.OBSIDIAN_SCRAP);
                       entries.add(ModItems.ENDERITE_SCRAP);

                       entries.add(ModItems.TIN_NUGGET);
                       entries.add(ModItems.SILVER_NUGGET);
                       entries.add(ModItems.COPPER_NUGGET);
                       entries.add(ModItems.STERLING_SILVER_NUGGET);
                       entries.add(ModItems.ROSE_GOLD_NUGGET);
                       entries.add(ModItems.BRONZE_NUGGET);
                       entries.add(ModItems.COBALT_NUGGET);
                       entries.add(ModItems.CARBON_STEEL_NUGGET);
                       entries.add(ModItems.HARDENED_STEEL_NUGGET);

                       entries.add(ModItems.AMETHYST_DUST);
                       entries.add(ModItems.QUARTZ_DUST);
                       entries.add(ModItems.LAPIS_LAZULI_DUST);
                       entries.add(ModItems.TURQUOISE_DUST);

                       entries.add(ModItems.TIN_INGOT);
                       entries.add(ModItems.BRONZE_INGOT);
                       entries.add(ModItems.SILVER_INGOT);
                       entries.add(ModItems.STERLING_SILVER_INGOT);
                       entries.add(ModItems.ROSE_GOLD_INGOT);
                       entries.add(ModItems.COBALT_INGOT);
                       entries.add(ModItems.CARBON_STEEL_INGOT);
                       entries.add(ModItems.HARDENED_STEEL_INGOT);
                       entries.add(ModItems.OBSIDIAN_INGOT);
                       entries.add(ModItems.ADAMANTIUM_INGOT);
                       entries.add(ModItems.ENDERITE_INGOT);

                       entries.add(ModItems.AMETHYST_GEM);
                       entries.add(ModItems.LAPIS_LAZULI_GEM);
                       entries.add(ModItems.TURQUOISE_GEM);
                       entries.add(ModItems.TOURMALINE_GEM);
                       entries.add(ModItems.TOPAZ_GEM);
                       entries.add(ModItems.RUBY_GEM);
                       entries.add(ModItems.SAPPHIRE_GEM);
                       entries.add(ModItems.SPINEL_GEM);
                       entries.add(ModItems.CITRINE_GEM);
                       entries.add(ModItems.MOISSANITE_GEM);
                       entries.add(ModItems.ONYX_GEM);
                       entries.add(ModItems.GRAPHENE_CHAINMAIL);
                    }).build());
    public static final ItemGroup BLOCK_GROUP = Registry.register(Registries.ITEM_GROUP,
            Identifier.of(Mores.MOD_ID, "blocks"),
            FabricItemGroup.builder().displayName(Text.translatable("creativemodetab.mores_blocks"))
                    .icon(() -> new ItemStack(ModBlocks.TURQUOISE_BLOCK)).entries((displayContext, entries) -> {
                        entries.add(ModBlocks.ALLOY_FURNACE);
                        entries.add(ModBlocks.STEEL_CUTTER);
                        entries.add(ModBlocks.LEMON_OAK_LEAVES);
                        entries.add(ModBlocks.LEMON_OAK_SAPLING);
                        entries.add(ModBlocks.RAW_TIN_BLOCK);
                        entries.add(ModBlocks.RAW_SILVER_BLOCK);
                        entries.add(ModBlocks.RAW_COBALT_BLOCK);
                        entries.add(ModBlocks.TIN_BLOCK);
                        entries.add(ModBlocks.SILVER_BLOCK);
                        entries.add(ModBlocks.STERLING_SILVER_BLOCK);
                        entries.add(ModBlocks.ROSE_GOLD_BLOCK);
                        entries.add(ModBlocks.BRONZE_BLOCK);
                        entries.add(ModBlocks.COBALT_BLOCK);
                        entries.add(ModBlocks.CARBON_STEEL_BLOCK);
                        entries.add(ModBlocks.HARDENED_STEEL_BLOCK);
                        entries.add(ModBlocks.TURQUOISE_BLOCK);
                        entries.add(ModBlocks.CITRINE_BLOCK);
                        entries.add(ModBlocks.ONYX_BLOCK);
                        entries.add(ModBlocks.TANZANITE_BLOCK);
                        entries.add(ModBlocks.TOURMALINE_BLOCK);
                        entries.add(ModBlocks.TOPAZ_BLOCK);
                        entries.add(ModBlocks.RUBY_BLOCK);
                        entries.add(ModBlocks.SAPPHIRE_BLOCK);
                        entries.add(ModBlocks.SPINEL_BLOCK);
                        entries.add(ModBlocks.MOISSANITE_BLOCK);
                        entries.add(ModBlocks.ADAMANTIUM_BLOCK);
                        entries.add(ModBlocks.ENDERITE_BLOCK);
                    }).build());

    public static final ItemGroup ORE_GROUP = Registry.register(Registries.ITEM_GROUP,
            Identifier.of(Mores.MOD_ID, "ores"),
            FabricItemGroup.builder().displayName(Text.translatable("creativemodetab.mores_ores"))
                    .icon(() -> new ItemStack(ModBlocks.DEEPSLATE_TURQUOISE_ORE)).entries((displayContext, entries) -> {
                        entries.add(ModBlocks.ANTHRACITE_ORE);
                        entries.add(ModBlocks.DEEPSLATE_ANTHRACITE_ORE);
                        entries.add(ModBlocks.NETHER_ANTHRACITE_ORE);
                        entries.add(ModBlocks.TIN_ORE);
                        entries.add(ModBlocks.DEEPSLATE_TIN_ORE);
                        entries.add(ModBlocks.ANDESITE_TIN_ORE);
                        entries.add(ModBlocks.GRANITE_TIN_ORE);
                        entries.add(ModBlocks.GRAVEL_TIN_ORE);
                        entries.add(ModBlocks.TUFF_TIN_ORE);
                        entries.add(ModBlocks.ELECTRUM_ORE);
                        entries.add(ModBlocks.SILVER_ORE);
                        entries.add(ModBlocks.NETHER_SILVER_ORE);
                        entries.add(ModBlocks.ENDER_SILVER_ORE);
                        entries.add(ModBlocks.DEEPSLATE_SILVER_ORE);
                        entries.add(ModBlocks.ANDESITE_SILVER_ORE);
                        entries.add(ModBlocks.BASALT_SILVER_ORE);
                        entries.add(ModBlocks.BLACKSTONE_SILVER_ORE);
                        entries.add(ModBlocks.CALCITE_SILVER_ORE);
                        entries.add(ModBlocks.DIORITE_SILVER_ORE);
                        entries.add(ModBlocks.GRANITE_SILVER_ORE);
                        entries.add(ModBlocks.GRAVEL_SILVER_ORE);
                        entries.add(ModBlocks.TUFF_SILVER_ORE);
                        entries.add(ModBlocks.COBALT_ORE);
                        entries.add(ModBlocks.DEEPSLATE_COBALT_ORE);
                        entries.add(ModBlocks.ENDER_COBALT_ORE);
                        entries.add(ModBlocks.ANDESITE_COBALT_ORE);
                        entries.add(ModBlocks.BASALT_COBALT_ORE);
                        entries.add(ModBlocks.BLACKSTONE_COBALT_ORE);
                        entries.add(ModBlocks.CALCITE_COBALT_ORE);
                        entries.add(ModBlocks.DIORITE_COBALT_ORE);
                        entries.add(ModBlocks.GRANITE_COBALT_ORE);
                        entries.add(ModBlocks.GRAVEL_COBALT_ORE);
                        entries.add(ModBlocks.TUFF_COBALT_ORE);
                        entries.add(ModBlocks.TURQUOISE_ORE);
                        entries.add(ModBlocks.DEEPSLATE_TURQUOISE_ORE);
                        entries.add(ModBlocks.QUARTZ_ORE);
                        entries.add(ModBlocks.CITRINE_ORE);
                        entries.add(ModBlocks.NETHER_CITRINE_ORE);
                        entries.add(ModBlocks.NETHER_ONYX_ORE);
                        entries.add(ModBlocks.ENDER_ONYX_ORE);
                        entries.add(ModBlocks.TANZANITE_ORE);
                        entries.add(ModBlocks.DEEPSLATE_TANZANITE_ORE);
                        entries.add(ModBlocks.NETHER_TANZANITE_ORE);
                        entries.add(ModBlocks.ENDER_TANZANITE_ORE);
                        entries.add(ModBlocks.ANDESITE_TANZANITE_ORE);
                        entries.add(ModBlocks.BASALT_TANZANITE_ORE);
                        entries.add(ModBlocks.BLACKSTONE_TANZANITE_ORE);
                        entries.add(ModBlocks.CALCITE_TANZANITE_ORE);
                        entries.add(ModBlocks.DIORITE_TANZANITE_ORE);
                        entries.add(ModBlocks.GRANITE_TANZANITE_ORE);
                        entries.add(ModBlocks.GRAVEL_TANZANITE_ORE);
                        entries.add(ModBlocks.TUFF_TANZANITE_ORE);
                        entries.add(ModBlocks.TOURMALINE_ORE);
                        entries.add(ModBlocks.DEEPSLATE_TOURMALINE_ORE);
                        entries.add(ModBlocks.NETHER_TOURMALINE_ORE);
                        entries.add(ModBlocks.ENDER_TOURMALINE_ORE);
                        entries.add(ModBlocks.ANDESITE_TOURMALINE_ORE);
                        entries.add(ModBlocks.BASALT_TOURMALINE_ORE);
                        entries.add(ModBlocks.BLACKSTONE_TOURMALINE_ORE);
                        entries.add(ModBlocks.CALCITE_TOURMALINE_ORE);
                        entries.add(ModBlocks.DIORITE_TOURMALINE_ORE);
                        entries.add(ModBlocks.GRANITE_TOURMALINE_ORE);
                        entries.add(ModBlocks.GRAVEL_TOURMALINE_ORE);
                        entries.add(ModBlocks.TUFF_TOURMALINE_ORE);
                        entries.add(ModBlocks.TOPAZ_ORE);
                        entries.add(ModBlocks.DEEPSLATE_TOPAZ_ORE);
                        entries.add(ModBlocks.NETHER_TOPAZ_ORE);
                        entries.add(ModBlocks.ENDER_TOPAZ_ORE);
                        entries.add(ModBlocks.ANDESITE_TOPAZ_ORE);
                        entries.add(ModBlocks.BASALT_TOPAZ_ORE);
                        entries.add(ModBlocks.BLACKSTONE_TOPAZ_ORE);
                        entries.add(ModBlocks.CALCITE_TOPAZ_ORE);
                        entries.add(ModBlocks.DIORITE_TOPAZ_ORE);
                        entries.add(ModBlocks.GRANITE_TOPAZ_ORE);
                        entries.add(ModBlocks.GRAVEL_TOPAZ_ORE);
                        entries.add(ModBlocks.TUFF_TOPAZ_ORE);
                        entries.add(ModBlocks.SPINEL_ORE);
                        entries.add(ModBlocks.DEEPSLATE_SPINEL_ORE);
                        entries.add(ModBlocks.NETHER_SPINEL_ORE);
                        entries.add(ModBlocks.ENDER_SPINEL_ORE);
                        entries.add(ModBlocks.ANDESITE_SPINEL_ORE);
                        entries.add(ModBlocks.BASALT_SPINEL_ORE);
                        entries.add(ModBlocks.BLACKSTONE_SPINEL_ORE);
                        entries.add(ModBlocks.CALCITE_SPINEL_ORE);
                        entries.add(ModBlocks.DIORITE_SPINEL_ORE);
                        entries.add(ModBlocks.GRANITE_SPINEL_ORE);
                        entries.add(ModBlocks.GRAVEL_SPINEL_ORE);
                        entries.add(ModBlocks.TUFF_SPINEL_ORE);
                        entries.add(ModBlocks.RUBY_ORE);
                        entries.add(ModBlocks.DEEPSLATE_RUBY_ORE);
                        entries.add(ModBlocks.NETHER_RUBY_ORE);
                        entries.add(ModBlocks.ENDER_RUBY_ORE);
                        entries.add(ModBlocks.ANDESITE_RUBY_ORE);
                        entries.add(ModBlocks.BASALT_RUBY_ORE);
                        entries.add(ModBlocks.BLACKSTONE_RUBY_ORE);
                        entries.add(ModBlocks.CALCITE_RUBY_ORE);
                        entries.add(ModBlocks.DIORITE_RUBY_ORE);
                        entries.add(ModBlocks.GRANITE_RUBY_ORE);
                        entries.add(ModBlocks.GRAVEL_RUBY_ORE);
                        entries.add(ModBlocks.TUFF_RUBY_ORE);
                        entries.add(ModBlocks.SAPPHIRE_ORE);
                        entries.add(ModBlocks.DEEPSLATE_SAPPHIRE_ORE);
                        entries.add(ModBlocks.NETHER_SAPPHIRE_ORE);
                        entries.add(ModBlocks.ENDER_SAPPHIRE_ORE);
                        entries.add(ModBlocks.ANDESITE_SAPPHIRE_ORE);
                        entries.add(ModBlocks.BASALT_SAPPHIRE_ORE);
                        entries.add(ModBlocks.BLACKSTONE_SAPPHIRE_ORE);
                        entries.add(ModBlocks.CALCITE_SAPPHIRE_ORE);
                        entries.add(ModBlocks.DIORITE_SAPPHIRE_ORE);
                        entries.add(ModBlocks.GRANITE_SAPPHIRE_ORE);
                        entries.add(ModBlocks.GRAVEL_SAPPHIRE_ORE);
                        entries.add(ModBlocks.TUFF_SAPPHIRE_ORE);
                        entries.add(ModBlocks.MOISSANITE_ORE);
                        entries.add(ModBlocks.DEEPSLATE_MOISSANITE_ORE);
                        entries.add(ModBlocks.NETHER_MOISSANITE_ORE);
                        entries.add(ModBlocks.ENDER_MOISSANITE_ORE);
                        entries.add(ModBlocks.ANDESITE_MOISSANITE_ORE);
                        entries.add(ModBlocks.BASALT_MOISSANITE_ORE);
                        entries.add(ModBlocks.BLACKSTONE_MOISSANITE_ORE);
                        entries.add(ModBlocks.CALCITE_MOISSANITE_ORE);
                        entries.add(ModBlocks.DIORITE_MOISSANITE_ORE);
                        entries.add(ModBlocks.GRANITE_MOISSANITE_ORE);
                        entries.add(ModBlocks.GRAVEL_MOISSANITE_ORE);
                        entries.add(ModBlocks.TUFF_MOISSANITE_ORE);
                        entries.add(ModBlocks.PRIMORDIAL_DEBRIS);
                    }).build());

    public static final ItemGroup TOOLS_GROUP = Registry.register(Registries.ITEM_GROUP,
            Identifier.of(Mores.MOD_ID, "tools"),
            FabricItemGroup.builder().displayName(Text.translatable("creativemodetab.mores_tools"))
                    .icon(() -> new ItemStack(ModItems.COBALT_PICKAXE)).entries((displayContext, entries) -> {
                        entries.add(ModItems.TIN_PICKAXE);
                        entries.add(ModItems.TIN_AXE);
                        entries.add(ModItems.TIN_SHOVEL);
                        entries.add(ModItems.TIN_HOE);
                        entries.add(ModItems.SILVER_PICKAXE);
                        entries.add(ModItems.SILVER_AXE);
                        entries.add(ModItems.SILVER_SHOVEL);
                        entries.add(ModItems.SILVER_HOE);
                        entries.add(ModItems.COPPER_PICKAXE);
                        entries.add(ModItems.COPPER_AXE);
                        entries.add(ModItems.COPPER_SHOVEL);
                        entries.add(ModItems.COPPER_HOE);
                        entries.add(ModItems.STERLING_SILVER_PICKAXE);
                        entries.add(ModItems.STERLING_SILVER_AXE);
                        entries.add(ModItems.STERLING_SILVER_SHOVEL);
                        entries.add(ModItems.STERLING_SILVER_HOE);
                        entries.add(ModItems.ROSE_GOLD_PICKAXE);
                        entries.add(ModItems.ROSE_GOLD_AXE);
                        entries.add(ModItems.ROSE_GOLD_SHOVEL);
                        entries.add(ModItems.ROSE_GOLD_HOE);
                        entries.add(ModItems.BRONZE_PICKAXE);
                        entries.add(ModItems.BRONZE_AXE);
                        entries.add(ModItems.BRONZE_SHOVEL);
                        entries.add(ModItems.BRONZE_HOE);
                        entries.add(ModItems.COBALT_PICKAXE);
                        entries.add(ModItems.COBALT_AXE);
                        entries.add(ModItems.COBALT_SHOVEL);
                        entries.add(ModItems.COBALT_HOE);
                        entries.add(ModItems.CARBON_STEEL_PICKAXE);
                        entries.add(ModItems.CARBON_STEEL_AXE);
                        entries.add(ModItems.CARBON_STEEL_SHOVEL);
                        entries.add(ModItems.CARBON_STEEL_HOE);
                        entries.add(ModItems.HARDENED_STEEL_PICKAXE);
                        entries.add(ModItems.HARDENED_STEEL_AXE);
                        entries.add(ModItems.HARDENED_STEEL_SHOVEL);
                        entries.add(ModItems.HARDENED_STEEL_HOE);
                        entries.add(ModItems.TURQUOISE_PICKAXE);
                        entries.add(ModItems.TURQUOISE_AXE);
                        entries.add(ModItems.TURQUOISE_SHOVEL);
                        entries.add(ModItems.TURQUOISE_HOE);
                        entries.add(ModItems.LAPIS_LAZULI_PICKAXE);
                        entries.add(ModItems.LAPIS_LAZULI_AXE);
                        entries.add(ModItems.LAPIS_LAZULI_SHOVEL);
                        entries.add(ModItems.LAPIS_LAZULI_HOE);
                        entries.add(ModItems.AMETHYST_PICKAXE);
                        entries.add(ModItems.AMETHYST_AXE);
                        entries.add(ModItems.AMETHYST_SHOVEL);
                        entries.add(ModItems.AMETHYST_HOE);
                        entries.add(ModItems.ONYX_PICKAXE);
                        entries.add(ModItems.ONYX_AXE);
                        entries.add(ModItems.ONYX_SHOVEL);
                        entries.add(ModItems.ONYX_HOE);
                        entries.add(ModItems.CITRINE_PICKAXE);
                        entries.add(ModItems.CITRINE_AXE);
                        entries.add(ModItems.CITRINE_SHOVEL);
                        entries.add(ModItems.CITRINE_HOE);
                        entries.add(ModItems.TANZANITE_PICKAXE);
                        entries.add(ModItems.TANZANITE_AXE);
                        entries.add(ModItems.TANZANITE_SHOVEL);
                        entries.add(ModItems.TANZANITE_HOE);
                        entries.add(ModItems.TOURMALINE_PICKAXE);
                        entries.add(ModItems.TOURMALINE_AXE);
                        entries.add(ModItems.TOURMALINE_SHOVEL);
                        entries.add(ModItems.TOURMALINE_HOE);
                        entries.add(ModItems.TOPAZ_PICKAXE);
                        entries.add(ModItems.TOPAZ_AXE);
                        entries.add(ModItems.TOPAZ_SHOVEL);
                        entries.add(ModItems.TOPAZ_HOE);
                        entries.add(ModItems.SPINEL_PICKAXE);
                        entries.add(ModItems.SPINEL_AXE);
                        entries.add(ModItems.SPINEL_SHOVEL);
                        entries.add(ModItems.SPINEL_HOE);
                        entries.add(ModItems.EMERALD_PICKAXE);
                        entries.add(ModItems.EMERALD_AXE);
                        entries.add(ModItems.EMERALD_SHOVEL);
                        entries.add(ModItems.EMERALD_HOE);
                        entries.add(ModItems.RUBY_PICKAXE);
                        entries.add(ModItems.RUBY_AXE);
                        entries.add(ModItems.RUBY_SHOVEL);
                        entries.add(ModItems.RUBY_HOE);
                        entries.add(ModItems.SAPPHIRE_PICKAXE);
                        entries.add(ModItems.SAPPHIRE_AXE);
                        entries.add(ModItems.SAPPHIRE_SHOVEL);
                        entries.add(ModItems.SAPPHIRE_HOE);
                        entries.add(ModItems.MOISSANITE_PICKAXE);
                        entries.add(ModItems.MOISSANITE_AXE);
                        entries.add(ModItems.MOISSANITE_SHOVEL);
                        entries.add(ModItems.MOISSANITE_HOE);
//                        entries.add(ModItems.GRAPHENE_PICKAXE);
//                        entries.add(ModItems.GRAPHENE_AXE);
//                        entries.add(ModItems.GRAPHENE_SHOVEL);
//                        entries.add(ModItems.GRAPHENE_HOE);
                        entries.add(ModItems.OBSIDIAN_PICKAXE);
                        entries.add(ModItems.OBSIDIAN_AXE);
                        entries.add(ModItems.OBSIDIAN_SHOVEL);
                        entries.add(ModItems.OBSIDIAN_HOE);
                        entries.add(ModItems.ADAMANTIUM_PICKAXE);
                        entries.add(ModItems.ADAMANTIUM_AXE);
                        entries.add(ModItems.ADAMANTIUM_SHOVEL);
                        entries.add(ModItems.ADAMANTIUM_HOE);
                        entries.add(ModItems.ENDERITE_PICKAXE);
                        entries.add(ModItems.ENDERITE_AXE);
                        entries.add(ModItems.ENDERITE_SHOVEL);
                        entries.add(ModItems.ENDERITE_HOE);
                        entries.add(ModItems.SWEET_CAROLINE_MUSIC_DISC);
                        entries.add(ModItems.CIPHER_MUSIC_DISC);
                    }).build());

    public static final ItemGroup WEAPONS_GROUP = Registry.register(Registries.ITEM_GROUP,
            Identifier.of(Mores.MOD_ID, "weapons"),
            FabricItemGroup.builder().displayName(Text.translatable("creativemodetab.mores_weapons"))
                    .icon(() -> new ItemStack(ModItems.NETHERITE_BATTLE_AXE)).entries((displayContext, entries) -> {
                        entries.add(ModItems.WOOD_BATTLE_AXE);
                        entries.add(ModItems.WOOD_BATTLE_MACE);
                        entries.add(ModItems.WOOD_DAGGER);
                        entries.add(ModItems.STONE_BATTLE_AXE);
                        entries.add(ModItems.STONE_BATTLE_MACE);
                        entries.add(ModItems.STONE_DAGGER);
                        entries.add(ModItems.TIN_SWORD);
                        entries.add(ModItems.TIN_BATTLE_AXE);
                        entries.add(ModItems.TIN_BATTLE_MACE);
                        entries.add(ModItems.TIN_DAGGER);
                        entries.add(ModItems.GOLD_BATTLE_AXE);
                        entries.add(ModItems.GOLD_BATTLE_MACE);
                        entries.add(ModItems.GOLD_DAGGER);
                        entries.add(ModItems.SILVER_SWORD);
                        entries.add(ModItems.SILVER_BATTLE_AXE);
                        entries.add(ModItems.SILVER_BATTLE_MACE);
                        entries.add(ModItems.SILVER_DAGGER);
                        entries.add(ModItems.COPPER_SWORD);
                        entries.add(ModItems.COPPER_BATTLE_AXE);
                        entries.add(ModItems.COPPER_BATTLE_MACE);
                        entries.add(ModItems.COPPER_DAGGER);
                        entries.add(ModItems.STERLING_SILVER_SWORD);
                        entries.add(ModItems.STERLING_SILVER_BATTLE_AXE);
                        entries.add(ModItems.STERLING_SILVER_BATTLE_MACE);
                        entries.add(ModItems.STERLING_SILVER_DAGGER);
                        entries.add(ModItems.ROSE_GOLD_SWORD);
                        entries.add(ModItems.ROSE_GOLD_BATTLE_AXE);
                        entries.add(ModItems.ROSE_GOLD_BATTLE_MACE);
                        entries.add(ModItems.ROSE_GOLD_DAGGER);
                        if (ModItems.ROSE_GOLD_SPEAR != null) entries.add(ModItems.ROSE_GOLD_SPEAR);
                        entries.add(ModItems.BRONZE_SWORD);
                        entries.add(ModItems.BRONZE_BATTLE_AXE);
                        entries.add(ModItems.BRONZE_BATTLE_MACE);
                        entries.add(ModItems.BRONZE_DAGGER);
                        entries.add(ModItems.IRON_BATTLE_AXE);
                        entries.add(ModItems.IRON_BATTLE_MACE);
                        entries.add(ModItems.IRON_DAGGER);
                        entries.add(ModItems.COBALT_SWORD);
                        entries.add(ModItems.COBALT_BATTLE_AXE);
                        entries.add(ModItems.COBALT_BATTLE_MACE);
                        entries.add(ModItems.COBALT_DAGGER);
                        entries.add(ModItems.CARBON_STEEL_SWORD);
                        entries.add(ModItems.CARBON_STEEL_BATTLE_AXE);
                        entries.add(ModItems.CARBON_STEEL_BATTLE_MACE);
                        entries.add(ModItems.CARBON_STEEL_DAGGER);
                        if (ModItems.CARBON_STEEL_SPEAR != null) entries.add(ModItems.CARBON_STEEL_SPEAR);
                        entries.add(ModItems.HARDENED_STEEL_SWORD);
                        entries.add(ModItems.HARDENED_STEEL_BATTLE_AXE);
                        entries.add(ModItems.HARDENED_STEEL_BATTLE_MACE);
                        entries.add(ModItems.HARDENED_STEEL_DAGGER);
                        if (ModItems.HARDENED_STEEL_SPEAR != null) entries.add(ModItems.HARDENED_STEEL_SPEAR);
                        entries.add(ModItems.TURQUOISE_SWORD);
                        entries.add(ModItems.TURQUOISE_BATTLE_AXE);
                        entries.add(ModItems.TURQUOISE_BATTLE_MACE);
                        entries.add(ModItems.TURQUOISE_DAGGER);
                        entries.add(ModItems.LAPIS_LAZULI_SWORD);
                        entries.add(ModItems.LAPIS_LAZULI_BATTLE_AXE);
                        entries.add(ModItems.LAPIS_LAZULI_BATTLE_MACE);
                        entries.add(ModItems.LAPIS_LAZULI_DAGGER);
                        entries.add(ModItems.AMETHYST_SWORD);
                        entries.add(ModItems.AMETHYST_BATTLE_AXE);
                        entries.add(ModItems.AMETHYST_BATTLE_MACE);
                        entries.add(ModItems.AMETHYST_DAGGER);
                        entries.add(ModItems.ONYX_SWORD);
                        entries.add(ModItems.ONYX_BATTLE_AXE);
                        entries.add(ModItems.ONYX_BATTLE_MACE);
                        entries.add(ModItems.ONYX_DAGGER);
                        entries.add(ModItems.CITRINE_SWORD);
                        entries.add(ModItems.CITRINE_BATTLE_AXE);
                        entries.add(ModItems.CITRINE_BATTLE_MACE);
                        entries.add(ModItems.CITRINE_DAGGER);
                        entries.add(ModItems.TANZANITE_SWORD);
                        entries.add(ModItems.TANZANITE_BATTLE_AXE);
                        entries.add(ModItems.TANZANITE_BATTLE_MACE);
                        entries.add(ModItems.TANZANITE_DAGGER);
                        entries.add(ModItems.TOURMALINE_SWORD);
                        entries.add(ModItems.TOURMALINE_BATTLE_AXE);
                        entries.add(ModItems.TOURMALINE_BATTLE_MACE);
                        entries.add(ModItems.TOURMALINE_DAGGER);
                        entries.add(ModItems.TOPAZ_SWORD);
                        entries.add(ModItems.TOPAZ_BATTLE_AXE);
                        entries.add(ModItems.TOPAZ_BATTLE_MACE);
                        entries.add(ModItems.TOPAZ_DAGGER);
                        entries.add(ModItems.SPINEL_SWORD);
                        entries.add(ModItems.SPINEL_BATTLE_AXE);
                        entries.add(ModItems.SPINEL_BATTLE_MACE);
                        entries.add(ModItems.SPINEL_DAGGER);
                        entries.add(ModItems.EMERALD_SWORD);
                        entries.add(ModItems.EMERALD_BATTLE_AXE);
                        entries.add(ModItems.EMERALD_BATTLE_MACE);
                        entries.add(ModItems.EMERALD_DAGGER);
                        entries.add(ModItems.DIAMOND_BATTLE_AXE);
                        entries.add(ModItems.DIAMOND_BATTLE_MACE);
                        entries.add(ModItems.DIAMOND_DAGGER);
                        entries.add(ModItems.RUBY_SWORD);
                        entries.add(ModItems.RUBY_BATTLE_AXE);
                        entries.add(ModItems.RUBY_BATTLE_MACE);
                        entries.add(ModItems.RUBY_DAGGER);
                        entries.add(ModItems.SAPPHIRE_SWORD);
                        entries.add(ModItems.SAPPHIRE_BATTLE_AXE);
                        entries.add(ModItems.SAPPHIRE_BATTLE_MACE);
                        entries.add(ModItems.SAPPHIRE_DAGGER);
                        entries.add(ModItems.MOISSANITE_SWORD);
                        entries.add(ModItems.MOISSANITE_BATTLE_AXE);
                        entries.add(ModItems.MOISSANITE_BATTLE_MACE);
                        entries.add(ModItems.MOISSANITE_DAGGER);
//                        entries.add(ModItems.GRAPHENE_SWORD);
//                        entries.add(ModItems.GRAPHENE_BATTLE_AXE);
//                        entries.add(ModItems.GRAPHENE_BATTLE_MACE);
//                        entries.add(ModItems.GRAPHENE_DAGGER);
                        entries.add(ModItems.OBSIDIAN_SWORD);
                        entries.add(ModItems.OBSIDIAN_BATTLE_AXE);
                        entries.add(ModItems.OBSIDIAN_BATTLE_MACE);
                        entries.add(ModItems.OBSIDIAN_DAGGER);
                        entries.add(ModItems.ADAMANTIUM_SWORD);
                        entries.add(ModItems.ADAMANTIUM_BATTLE_AXE);
                        entries.add(ModItems.ADAMANTIUM_BATTLE_MACE);
                        entries.add(ModItems.ADAMANTIUM_DAGGER);
                        entries.add(ModItems.NETHERITE_BATTLE_AXE);
                        entries.add(ModItems.NETHERITE_BATTLE_MACE);
                        entries.add(ModItems.NETHERITE_DAGGER);
                        entries.add(ModItems.ENDERITE_SWORD);
                        entries.add(ModItems.ENDERITE_BATTLE_AXE);
                        entries.add(ModItems.ENDERITE_BATTLE_MACE);
                        entries.add(ModItems.ENDERITE_DAGGER);
                        if (ModItems.ENDERITE_SPEAR != null) entries.add(ModItems.ENDERITE_SPEAR);
                    }).build());

    public static final ItemGroup ARMOR_GROUP = Registry.register(Registries.ITEM_GROUP,
            Identifier.of(Mores.MOD_ID, "armor"),
            FabricItemGroup.builder().displayName(Text.translatable("creativemodetab.mores_armor"))
                    .icon(() -> new ItemStack(ModItems.GRAPHENE_CHAINMAIL_CHESTPLATE)).entries((displayContext, entries) -> {
                        entries.add(ModItems.TIN_HELMET);
                        entries.add(ModItems.TIN_CHESTPLATE);
                        entries.add(ModItems.TIN_LEGGINGS);
                        entries.add(ModItems.TIN_BOOTS);
                        entries.add(ModItems.SILVER_HELMET);
                        entries.add(ModItems.SILVER_CHESTPLATE);
                        entries.add(ModItems.SILVER_LEGGINGS);
                        entries.add(ModItems.SILVER_BOOTS);
                        entries.add(ModItems.COPPER_HELMET);
                        entries.add(ModItems.COPPER_CHESTPLATE);
                        entries.add(ModItems.COPPER_LEGGINGS);
                        entries.add(ModItems.COPPER_BOOTS);
                        entries.add(ModItems.STERLING_SILVER_HELMET);
                        entries.add(ModItems.STERLING_SILVER_CHESTPLATE);
                        entries.add(ModItems.STERLING_SILVER_LEGGINGS);
                        entries.add(ModItems.STERLING_SILVER_BOOTS);
                        entries.add(ModItems.BRONZE_HELMET);
                        entries.add(ModItems.BRONZE_CHESTPLATE);
                        entries.add(ModItems.BRONZE_LEGGINGS);
                        entries.add(ModItems.BRONZE_BOOTS);
                        entries.add(ModItems.COBALT_HELMET);
                        entries.add(ModItems.COBALT_CHESTPLATE);
                        entries.add(ModItems.COBALT_LEGGINGS);
                        entries.add(ModItems.COBALT_BOOTS);
                        entries.add(ModItems.CARBON_STEEL_HELMET);
                        entries.add(ModItems.CARBON_STEEL_CHESTPLATE);
                        entries.add(ModItems.CARBON_STEEL_LEGGINGS);
                        entries.add(ModItems.CARBON_STEEL_BOOTS);
                        entries.add(ModItems.HARDENED_STEEL_HELMET);
                        entries.add(ModItems.HARDENED_STEEL_CHESTPLATE);
                        entries.add(ModItems.HARDENED_STEEL_LEGGINGS);
                        entries.add(ModItems.HARDENED_STEEL_BOOTS);
                        entries.add(ModItems.TURQUOISE_HELMET);
                        entries.add(ModItems.TURQUOISE_CHESTPLATE);
                        entries.add(ModItems.TURQUOISE_LEGGINGS);
                        entries.add(ModItems.TURQUOISE_BOOTS);
                        entries.add(ModItems.LAPIS_LAZULI_HELMET);
                        entries.add(ModItems.LAPIS_LAZULI_CHESTPLATE);
                        entries.add(ModItems.LAPIS_LAZULI_LEGGINGS);
                        entries.add(ModItems.LAPIS_LAZULI_BOOTS);
                        entries.add(ModItems.AMETHYST_HELMET);
                        entries.add(ModItems.AMETHYST_CHESTPLATE);
                        entries.add(ModItems.AMETHYST_LEGGINGS);
                        entries.add(ModItems.AMETHYST_BOOTS);
                        entries.add(ModItems.ONYX_HELMET);
                        entries.add(ModItems.ONYX_CHESTPLATE);
                        entries.add(ModItems.ONYX_LEGGINGS);
                        entries.add(ModItems.ONYX_BOOTS);
                        entries.add(ModItems.CITRINE_HELMET);
                        entries.add(ModItems.CITRINE_CHESTPLATE);
                        entries.add(ModItems.CITRINE_LEGGINGS);
                        entries.add(ModItems.CITRINE_BOOTS);
                        entries.add(ModItems.TANZANITE_HELMET);
                        entries.add(ModItems.TANZANITE_CHESTPLATE);
                        entries.add(ModItems.TANZANITE_LEGGINGS);
                        entries.add(ModItems.TANZANITE_BOOTS);
                        entries.add(ModItems.TOURMALINE_HELMET);
                        entries.add(ModItems.TOURMALINE_CHESTPLATE);
                        entries.add(ModItems.TOURMALINE_LEGGINGS);
                        entries.add(ModItems.TOURMALINE_BOOTS);
                        entries.add(ModItems.TOPAZ_HELMET);
                        entries.add(ModItems.TOPAZ_CHESTPLATE);
                        entries.add(ModItems.TOPAZ_LEGGINGS);
                        entries.add(ModItems.TOPAZ_BOOTS);
                        entries.add(ModItems.SPINEL_HELMET);
                        entries.add(ModItems.SPINEL_CHESTPLATE);
                        entries.add(ModItems.SPINEL_LEGGINGS);
                        entries.add(ModItems.SPINEL_BOOTS);
                        entries.add(ModItems.EMERALD_HELMET);
                        entries.add(ModItems.EMERALD_CHESTPLATE);
                        entries.add(ModItems.EMERALD_LEGGINGS);
                        entries.add(ModItems.EMERALD_BOOTS);
                        entries.add(ModItems.RUBY_HELMET);
                        entries.add(ModItems.RUBY_CHESTPLATE);
                        entries.add(ModItems.RUBY_LEGGINGS);
                        entries.add(ModItems.RUBY_BOOTS);
                        entries.add(ModItems.SAPPHIRE_HELMET);
                        entries.add(ModItems.SAPPHIRE_CHESTPLATE);
                        entries.add(ModItems.SAPPHIRE_LEGGINGS);
                        entries.add(ModItems.SAPPHIRE_BOOTS);
                        entries.add(ModItems.MOISSANITE_HELMET);
                        entries.add(ModItems.MOISSANITE_CHESTPLATE);
                        entries.add(ModItems.MOISSANITE_LEGGINGS);
                        entries.add(ModItems.MOISSANITE_BOOTS);
                        entries.add(ModItems.GRAPHENE_CHAINMAIL_HELMET);
                        entries.add(ModItems.GRAPHENE_CHAINMAIL_CHESTPLATE);
                        entries.add(ModItems.GRAPHENE_CHAINMAIL_LEGGINGS);
                        entries.add(ModItems.GRAPHENE_CHAINMAIL_BOOTS);
                        entries.add(ModItems.OBSIDIAN_HELMET);
                        entries.add(ModItems.OBSIDIAN_CHESTPLATE);
                        entries.add(ModItems.OBSIDIAN_LEGGINGS);
                        entries.add(ModItems.OBSIDIAN_BOOTS);
                        entries.add(ModItems.ADAMANTIUM_HELMET);
                        entries.add(ModItems.ADAMANTIUM_CHESTPLATE);
                        entries.add(ModItems.ADAMANTIUM_LEGGINGS);
                        entries.add(ModItems.ADAMANTIUM_BOOTS);
                        entries.add(ModItems.ENDERITE_HELMET);
                        entries.add(ModItems.ENDERITE_CHESTPLATE);
                        entries.add(ModItems.ENDERITE_LEGGINGS);
                        entries.add(ModItems.ENDERITE_BOOTS);
                    }).build());

    public static final ItemGroup SHIELDS_GROUP = Registry.register(Registries.ITEM_GROUP,
            Identifier.of(Mores.MOD_ID, "shields"),
            FabricItemGroup.builder().displayName(Text.translatable("creativemodetab.mores_shields"))
                    .icon(() -> new ItemStack(ModItems.BRONZE_SHIELD)).entries((displayContext, entries) -> {
                        entries.add(ModItems.TIN_SHIELD);
                        entries.add(ModItems.SILVER_SHIELD);
                        entries.add(ModItems.COPPER_SHIELD);
                        entries.add(ModItems.STERLING_SILVER_SHIELD);
                        entries.add(ModItems.ROSE_GOLD_SHIELD);
                        entries.add(ModItems.BRONZE_SHIELD);
                        entries.add(ModItems.COBALT_SHIELD);
                        entries.add(ModItems.CARBON_STEEL_SHIELD);
                        entries.add(ModItems.TURQUOISE_SHIELD);
                        entries.add(ModItems.LAPIS_LAZULI_SHIELD);
                        entries.add(ModItems.AMETHYST_SHIELD);
                        entries.add(ModItems.ONYX_SHIELD);
                        entries.add(ModItems.CITRINE_SHIELD);
                        entries.add(ModItems.TANZANITE_SHIELD);
                        entries.add(ModItems.TOURMALINE_SHIELD);
                        entries.add(ModItems.TOPAZ_SHIELD);
                        entries.add(ModItems.SPINEL_SHIELD);
                        entries.add(ModItems.EMERALD_SHIELD);
                        entries.add(ModItems.RUBY_SHIELD);
                        entries.add(ModItems.SAPPHIRE_SHIELD);
                        entries.add(ModItems.MOISSANITE_SHIELD);
//                        entries.add(ModItems.GRAPHENE_SHIELD);
                        entries.add(ModItems.OBSIDIAN_SHIELD);
                        entries.add(ModItems.ADAMANTIUM_SHIELD);
                        entries.add(ModItems.ENDERITE_SHIELD);
                    }).build());

        public static final ItemGroup ANIMAL_ARMOR_GROUP = Registry.register(Registries.ITEM_GROUP,
            Identifier.of(Mores.MOD_ID, "animal_armor"),
            FabricItemGroup.builder().displayName(Text.translatable("creativemodetab.mores_animal_armor"))
                    .icon(() -> new ItemStack(ModItems.TOURMALINE_HORSE_ARMOR)).entries((displayContext, entries) -> {
                        entries.add(ModItems.TIN_HORSE_ARMOR);
                        entries.add(ModItems.TIN_WOLF_ARMOR);
                        entries.add(ModItems.SILVER_HORSE_ARMOR);
                        entries.add(ModItems.SILVER_WOLF_ARMOR);
                        entries.add(ModItems.COPPER_HORSE_ARMOR);
                        entries.add(ModItems.COPPER_WOLF_ARMOR);
                        entries.add(ModItems.STERLING_SILVER_HORSE_ARMOR);
                        entries.add(ModItems.STERLING_SILVER_WOLF_ARMOR);
                        entries.add(ModItems.ROSE_GOLD_HORSE_ARMOR);
                        entries.add(ModItems.ROSE_GOLD_WOLF_ARMOR);
                        entries.add(ModItems.BRONZE_HORSE_ARMOR);
                        entries.add(ModItems.BRONZE_WOLF_ARMOR);
                        entries.add(ModItems.COBALT_HORSE_ARMOR);
                        entries.add(ModItems.COBALT_WOLF_ARMOR);
                        entries.add(ModItems.CARBON_STEEL_HORSE_ARMOR);
                        entries.add(ModItems.CARBON_STEEL_WOLF_ARMOR);
                        entries.add(ModItems.HARDENED_STEEL_HORSE_ARMOR);
                        entries.add(ModItems.HARDENED_STEEL_WOLF_ARMOR);
                        entries.add(ModItems.TURQUOISE_HORSE_ARMOR);
                        entries.add(ModItems.LAPIS_LAZULI_HORSE_ARMOR);
                        entries.add(ModItems.AMETHYST_HORSE_ARMOR);
                        entries.add(ModItems.ONYX_HORSE_ARMOR);
                        entries.add(ModItems.CITRINE_HORSE_ARMOR);
                        entries.add(ModItems.TANZANITE_HORSE_ARMOR);
                        entries.add(ModItems.TOURMALINE_HORSE_ARMOR);
                        entries.add(ModItems.TOPAZ_HORSE_ARMOR);
                        entries.add(ModItems.SPINEL_HORSE_ARMOR);
                        entries.add(ModItems.EMERALD_HORSE_ARMOR);
                        entries.add(ModItems.RUBY_HORSE_ARMOR);
                        entries.add(ModItems.SAPPHIRE_HORSE_ARMOR);
                        entries.add(ModItems.MOISSANITE_HORSE_ARMOR);
//                        entries.add(ModItems.GRAPHENE_HORSE_ARMOR);
                        entries.add(ModItems.OBSIDIAN_HORSE_ARMOR);
                        entries.add(ModItems.NETHERITE_HORSE_ARMOR);
                        entries.add(ModItems.ADAMANTIUM_HORSE_ARMOR);
                        entries.add(ModItems.ENDERITE_HORSE_ARMOR);
                    }).build());
//
    public static final ItemGroup FOOD_GROUP = Registry.register(Registries.ITEM_GROUP,
            Identifier.of(Mores.MOD_ID, "food"),
            FabricItemGroup.builder().displayName(Text.translatable("creativemodetab.mores_foods"))
                    .icon(() -> new ItemStack(ModItems.COBALT_APPLE)).entries((displayContext, entries) -> {
                        entries.add(ModItems.DARK_CHOCOLATE);
                        entries.add(ModItems.MILK_CHOCOLATE);
                        entries.add(ModItems.WHITE_CHOCOLATE);
                        entries.add(ModItems.APPLE_PIE);
                        entries.add(ModItems.BRONZE_APPLE);
                        entries.add(ModItems.COBALT_APPLE);
                        entries.add(ModItems.ENCHANTED_COBALT_APPLE);
                        entries.add(ModItems.SILVER_APPLE);
                        entries.add(ModItems.SILVER_CARROT);
                        entries.add(ModItems.LEMON);
                        entries.add(ModItems.LEMON_PIE);
                        entries.add(ModItems.CARROT_PIE);
                        entries.add(ModItems.VELVET);
                        entries.add(ModItems.SWEET_BERRY_PIE);
                        entries.add(ModItems.RAW_DUCK);
                        entries.add(ModItems.COOKED_DUCK);
                    }).build());

//    public static final ItemGroup ENTITIES_GROUP = Registry.register(Registries.ITEM_GROUP,
//            Identifier.of(Mores.MOD_ID, "Entities"),
//            FabricItemGroup.builder().displayName(Text.translatable("creativemodetab.mores_entities"))
//                    .icon(() -> new ItemStack(ModItems.DUCK_SPAWN_EGG)).entries((displayContext, entries) -> {
//                        entries.add(ModItems.DUCK_SPAWN_EGG);
//                    }).build());

    public static void registerItemGroups() {

    }
}